name: flutter_biometric_kit
description: A reusable Flutter library for biometric authentication using local_auth v3.
version: 1.0.0

environment:
  sdk: ^3.11.0
  flutter: ">=3.11.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^3.0.1
  local_auth_android: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_biometric_kit
        pluginClass: FlutterBiometricKitPlugin
      ios:
        pluginClass: FlutterBiometricKitPlugin